# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addexistingproduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_addprod(object):
    def setupUi_addprod(self, Form):
        Form.setObjectName("Form")
        Form.resize(2570, 1300)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-50, -60, 2621, 1361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,80);\n"
"background-image: url(:/images/background2);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.addnewbtn = QtWidgets.QPushButton(Form)
        self.addnewbtn.setGeometry(QtCore.QRect(1000, 750, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addnewbtn.setFont(font)
        self.addnewbtn.setObjectName("addnewbtn")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setGeometry(QtCore.QRect(720, 280, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.id.setAlignment(QtCore.Qt.AlignCenter)
        self.id.setObjectName("id")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(720, 360, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(720, 630, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.unitprice = QtWidgets.QLineEdit(Form)
        self.unitprice.setGeometry(QtCore.QRect(720, 540, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unitprice.setFont(font)
        self.unitprice.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.unitprice.setAlignment(QtCore.Qt.AlignCenter)
        self.unitprice.setObjectName("unitprice")
        self.resetbtn = QtWidgets.QPushButton(Form)
        self.resetbtn.setGeometry(QtCore.QRect(220, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.resetbtn.setFont(font)
        self.resetbtn.setObjectName("resetbtn")
        self.unitprice_2 = QtWidgets.QLineEdit(Form)
        self.unitprice_2.setGeometry(QtCore.QRect(720, 450, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unitprice_2.setFont(font)
        self.unitprice_2.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.unitprice_2.setAlignment(QtCore.Qt.AlignCenter)
        self.unitprice_2.setObjectName("unitprice_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addnewbtn.setText(_translate("Form", "Add Product"))
        self.pushButton_4.setText(_translate("Form", "Back"))
        self.id.setPlaceholderText(_translate("Form", "Product Id"))
        self.name.setPlaceholderText(_translate("Form", "Product Name"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Date of Purchase"))
        self.unitprice.setPlaceholderText(_translate("Form", "Unit Price"))
        self.resetbtn.setText(_translate("Form", "Reset"))
        self.unitprice_2.setPlaceholderText(_translate("Form", "Quantity"))
import storeman_res
