# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addnewproduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_addnewprod(object):
    def setupUi_addnewprod(self, Form):
        Form.setObjectName("Form")
        Form.resize(2570, 1300)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-50, -60, 2621, 1361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0,0,0,80);\n"
"background-image: url(:/images/background2);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.addnewbtn = QtWidgets.QPushButton(Form)
        self.addnewbtn.setGeometry(QtCore.QRect(950, 910, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addnewbtn.setFont(font)
        self.addnewbtn.setObjectName("addnewbtn")
        self.backbtn = QtWidgets.QPushButton(Form)
        self.backbtn.setGeometry(QtCore.QRect(10, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.backbtn.setFont(font)
        self.backbtn.setObjectName("backbtn")
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setGeometry(QtCore.QRect(720, 280, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id.setFont(font)
        self.id.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.id.setAlignment(QtCore.Qt.AlignCenter)
        self.id.setObjectName("id")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(720, 360, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.quantity = QtWidgets.QLineEdit(Form)
        self.quantity.setGeometry(QtCore.QRect(720, 530, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantity.setFont(font)
        self.quantity.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.catagory = QtWidgets.QLineEdit(Form)
        self.catagory.setGeometry(QtCore.QRect(720, 450, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.catagory.setFont(font)
        self.catagory.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.catagory.setAlignment(QtCore.Qt.AlignCenter)
        self.catagory.setObjectName("catagory")
        self.totalprice = QtWidgets.QLineEdit(Form)
        self.totalprice.setGeometry(QtCore.QRect(720, 700, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalprice.setFont(font)
        self.totalprice.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.totalprice.setAlignment(QtCore.Qt.AlignCenter)
        self.totalprice.setObjectName("totalprice")
        self.date = QtWidgets.QLineEdit(Form)
        self.date.setGeometry(QtCore.QRect(720, 790, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date.setFont(font)
        self.date.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.unitprice = QtWidgets.QLineEdit(Form)
        self.unitprice.setGeometry(QtCore.QRect(720, 620, 821, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.unitprice.setFont(font)
        self.unitprice.setStyleSheet("background-color:rgba(255,255,255,150);\n"
"border:none;\n"
"border-bottom: 2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"\n"
"")
        self.unitprice.setAlignment(QtCore.Qt.AlignCenter)
        self.unitprice.setObjectName("unitprice")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addnewbtn.setText(_translate("Form", "Add New Product"))
        self.backbtn.setText(_translate("Form", "Back"))
        self.id.setPlaceholderText(_translate("Form", "Product Id"))
        self.name.setPlaceholderText(_translate("Form", "Product Name"))
        self.quantity.setPlaceholderText(_translate("Form", "Purchased Quantity"))
        self.catagory.setPlaceholderText(_translate("Form", "Product Catagory"))
        self.totalprice.setPlaceholderText(_translate("Form", "Total Price"))
        self.date.setPlaceholderText(_translate("Form", "Date of Purchase"))
        self.unitprice.setPlaceholderText(_translate("Form", "Unit Price"))
        self.pushButton_5.setText(_translate("Form", "Reset"))
import storeman_res
